- name: Check Homebrew Is Installed
  stat:
    path: "{{ brew.bin_path }}/brew"
  register: "homebrew_check"

- name: Fail If Homebrew Is Not Installed
  fail:
    msg: "Homebrew is missing... Install brew from http://brew.sh/"
  when: not homebrew_check.stat.exists
