- name: Install Git
  homebrew: name=git state=present

- name: Add Global Git Congif Settings
  template: 
    src: "files/git/gitconfig.j2"
    dest: "{{ home_dir }}/.gitconfig"

- name: Add Global gitignore file
  copy: 
    src: "files/git/.gitignore_global"
    dest: "{{ home_dir }}/.gitignore_global"

# - name: Create bash_profile if it does not exist
#   file: state=touch path={{home_dir}}/.bash_profile
# 
# - name: Add aliases to bash_profile
#   blockinfile:
#     dest: "{{home_dir}}/.bash_profile"
#     content: |
#       #Git Alias
#       alias gs='git status'
#       alias gpr='git pull --rebase'
#       alias push='git push'
#       alias gds='git diff --staged'
#       alias gap='git add -p'
#       alias gcm='git commit -m'
#       alias oneline='git log --oneline'
