- name: Check nvm install
  shell: command -v nvm
  register: nvm_result
  check_mode: no
  failed_when: nvm_result.rc == 0

- name: Install nvm
  shell: >
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
  when: nvm_result.rc != 0

- name: Source nvm in ~/.profile
  become: yes
  become_user: "{{ nvm.user }}"
  lineinfile: >
    dest=~/.profile
    line="source ~/.nvm/nvm.sh"
    create=yes

- name: Install Node.js {{ nvm.node_version }}
  command: sudo -iu {{ nvm.user }} nvm install {{ nvm.node_version }}
  register: nvm_install_result
  changed_when: "'already installed' not in nvm_install_result.stdout"
  args:
    warn: false

- name: Set default node version to {{ nvm.node_version }}
  command: sudo -iu {{ nvm.user }} nvm alias default {{ nvm.node_version }}
  args:
    warn: false
